### ISSUE TITLE
Replaced github repo source (although same name/url), webhook fails

### ISSUE THREAD

**Issue by dionjwa** [denoland/deno_registry2#238]
I have this deno module: https://deno.land/x/cloudseed@0.0.8

I have been refactoring my github repositories, and I have replaced the original underlying repository.

However:
 - the github URL is exactly the same: https://github.com/metapages/cloudseed-deno
 - the link to the right on the deno.land package correctly goes to the new repo
 - but the webhook gets a 409: `{"success":false,"error":"module name is registered to a different repository"}`

Is there a way to correct this? I don't see a way of going back to the original repository (I don't know which one it is, I probably deleted in in my refactoring).

I would really like to keep the package name (`cloudseed`) and not have e.g. `cloudseed2` or something. How can this be fixed, or can you update the underlying database?

Thanks! Deno is great!

**Comment by wperron** [comment]
deno.land/x is bounds to the ID of the repository, not its name, so if you deleted the original repository and recreated a new one, the ID changed and that's why the webhook is failing.

I'll need to make sure that the package does indeed belong to you and I'll update the database to point to the new repository. Note that any previously uploaded versions will stay up, and that creating new tags with the same version string will fail because that version already exists. I suggest you start versioning from the last version you uploaded before changing the repository.

**Comment by wperron** [comment]
I've updated the repo ID, the change should take effect on the next Webhook invocation. Let me know if there's anything else I can do.

**Comment by dionjwa** [comment]
Awesome, thank you very much!! Yes, I started the new repo version after the previous, so all good there. 

Thank you again!! Deno's URL packaging system is changing my life !

**Comment by wperron** [comment]
As an aside, something I think is really cool with how Deno allows you do import dependencies is that you can import from anywhere, included GitHub raw URLs or gists, so reaching out for a package name on a registry isn't something you need to do right off the bat :smile: It's a different habit to take, but it's pretty cool. `cloudseed` looks pretty cool, keep it up!

**Comment by iam-medvedev** [comment]
I got into exactly the same situation. @wperron can you help me please?

Deno module: https://deno.land/x/dosya@v1.2.0
Github repo: https://github.com/iam-medvedev/dosya

**Comment by lucacasonato** [comment]
@iam-medvedev I have fixed it for you.
