### ISSUE TITLE
search small bug

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno_registry2#285]
when search oak in /x modules I don't find it, instead I find list of modules starts with oak_ or oak-

**Comment by brianinoa** [comment]
@elycheikhsmail, What seems to be the bug is the manner in which the results are sorted when a query is given

**Comment by brianinoa** [comment]
I'd like to ask that I be able to try and improve this.

**Comment by elycheikhsmail** [comment]
> @elycheikhsmail, What seems to be the bug is the manner in which the results are sorted when a query is given

I'am wrong there are several result for searching "oak" but the don't number of pages needed for displaying resultats only information is next button to tel you still there some result.
when I search for "oak" oak wil be the first page result but isn't

**Comment by brianinoa** [comment]
@elycheikhsmail That's true, that appears to be more because of the way they chose to display the data.

In the codebase, it doesn't explicitly try to accomplish those things that you've mentioned.

i.e. 
Looking at the "denoland/dotland" repo the [Pagination Component](https://github.com/denoland/dotland/blob/cd43f5f4a8d2dcb8982f96c0265dde8c8d69a304/components/Pagination.tsx) only shows "Next"

**Comment by crowlKats** [comment]
Closing as this has been fixed
