### ISSUE TITLE
Breaking Denoify

### ISSUE THREAD

**Issue by garronej** [denoland/deno_registry2#40]
Hi,

The new mechanism is better indeed but it breaks [Denoify](https://github.com/garronej/denoify).  
that was heavily reliant on ``database.json``.  
The new REST API does allow us to list third party modules but does not allows getting the source GitHub repo or the latest TAG ( which is now the fallback version ). 

Is there any play to make the module registry consumable by third party services or do I have to find workarounds? 

Regards

**Comment by buttercubz** [comment]
@garronej 
i think you can use this as a replacement https://cdn.deno.land/MODULE/meta/versions.json https://cdn.deno.land/MODULE/versions/MODULE_VERSION/meta/meta.json

**Comment by garronej** [comment]
Thank you very much!

**Comment by garronej** [comment]
@buttercubz sorry to disturb again but is the REST API publicly available? If yes at what url?

**Comment by garronej** [comment]
@lucacasonato, unfortunately, I can't find a workaround. 
[Denoify](https://github.com/garronej/denoify) needs to know if a given GitHub repo has been submitted as a Deno module.  
In the current implementation to resolve this query, I have to do hundreds of GET request, it takes forever.  

Would you be open to adding such query parameter to the GET modules/ request? 
- `auth` Only list modules published by the given GitHub user or organization (not set by default)

Thanks for your work,
Best regards

**Comment by lucacasonato** [comment]
@garronej I could give you a query parameter for listing all modules for a certain repo (not user or org though).

**Comment by garronej** [comment]
That would work 👍🏻 it would be great. 
So there can be more than one module published by repo?!
I assume it happens when registering a module using a unique repo but different sub directories?

**Comment by cfjello** [comment]
Hi,
I do not know if it's down to this issue mentioned here, but I have noticed that a number of previous existing Deno Third Party Modules are now missing from https://deno.land/x. They are still listed, but clicking on them shows this error:

No uploaded versions
This module name has been reserved for a repository, but no versions have been uploaded yet. Modules that do not upload a version within 30 days of registration will be removed (...)

This is unfortunate, since my Deno apps depend on some of these modules, meaning that I will have to try and locate the Deno's old database.json file on github in order to figure out where these modules are stored on github and then change the import statements in my code.
Best Regards

**Comment by garronej** [comment]
@lucacasonato I found my way around it, thanks anyway!
