### ISSUE TITLE
Projects with dot in the name

### ISSUE THREAD

**Issue by lem0nify** [denoland/deno_registry2#55]
I'm not sure but looks like you broke something in the last update. Modules which have dot in their project names are not available now, for instance:

- https://deno.land/x/dblapi.ts
- https://deno.land/x/jpeg.ts

As a result, other modules that depend on them can no longer be installed if they are not already cached.

**Comment by lucacasonato** [comment]
This has nothing to do with the dots in the name. It just happens to be that some people have not updated their modules since we released the registry update.

**Comment by lem0nify** [comment]
@lucacasonato Why is `jpeg.ts` now located at https://deno.land/x/jpegts then?

**Comment by lucacasonato** [comment]
🤷 - the module author seems to have published it there now? We knew a few packages were going to break because they were unversioned (and we are sorry for any inconvenience this may have caused), but we reserved all modules to their original repositores so the authors could publish a version right away. Our new naming guidelines do not permit `.` in names (but old packages with names that include `.` were grandfathered in), so I take it some module authors just published under a new name.

**Comment by lem0nify** [comment]
@lucacasonato 
> Our new naming guidelines do not permit . in names

Why?

**Comment by lucacasonato** [comment]
> Why?

Because we try to minimize confusion when looking at modules, and having 3-4 modules with slightly different variants of the same name is very annoying (e.g `foo` `foo.js` `foojs` `foo_js` `foo-js`). The first step in that is to reduce the amount of different characters a module name can have (our set is `_`, `a-z`, and `0-9`). The second step that we will implement soon is to disallow any module names which are within 1-2 changes away from any other module name (levenshtein distance).
