### ISSUE TITLE
Add names to the lambdas in cloudformation templates

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_registry2#72]
This will allow version rollback for individual lambdas.

**Comment by wperron** [comment]
Did some tests and adding the `FunctionName` property to the Lambdas configuration doesn't solve the versioning problem. We can use the `AutoPublishAlias` property, but that creates a `AWS::Lambda::Alias` in addition to the ` AWS::Lambda::Version`, and we don't really need that alias. It's not a huge problem since the Unqualified version will always be pointing to the most recent version.

Feels like a good time to drop a comment to lobby for Terraform, as the fix for this problem would literally just been to add `publish = true` to the Lambda's config 😉

**Comment by lucacasonato** [comment]
I am open to using Terraform. I am not very familiar with it though. How does it work? Is it just a CLI or does it have a server side component we need to run? Can we import components from CloudFormation into Terraform (migrate the S3 bucket for example)?
